apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntunl-host-data
  namespace: ntunl
spec:
  accessModes:
    - ReadWriteOnce
  # k3s ships the "local-path" provisioner as the default StorageClass.
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
