name: Create Release

on:
  push:
    tags:
      - "release-*"

jobs:
  build_windows_and_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Publish NtunlClient (Windows x64)
        run: dotnet publish src/NtunlClient/NtunlClient.csproj --configuration Release --output publish/windows-x64/NtunlClient -r win-x64 --self-contained

      - name: Publish NtunlHost (Windows x64)
        run: dotnet publish src/NtunlHost/NtunlHost.csproj --configuration Release --output publish/windows-x64/NtunlHost -r win-x64 --self-contained

      - name: Publish NtunlClient (Linux x64)
        run: dotnet publish src/NtunlClient/NtunlClient.csproj --configuration Release --output publish/linux-x64/NtunlClient -r linux-x64 --self-contained

      - name: Publish NtunlHost (Linux x64)
        run: dotnet publish src/NtunlHost/NtunlHost.csproj --configuration Release --output publish/linux-x64/NtunlHost -r linux-x64 --self-contained

      - name: Generate NtunlClient ZIP (Windows x64)
        run: |
          cd publish/windows-x64/NtunlClient
          zip -r ../../../NtunlClient_windows_x64.zip .

      - name: Generate NtunlHost ZIP (Windows x64)
        run: |
          cd publish/windows-x64/NtunlHost
          zip -r ../../../NtunlHost_windows_x64.zip .

      - name: Generate NtunlClient ZIP (Linux x64)
        run: |
          cd publish/linux-x64/NtunlClient
          zip -r ../../../NtunlClient_linux_x64.zip .

      - name: Generate NtunlHost ZIP (Linux x64)
        run: |
          cd publish/linux-x64/NtunlHost
          zip -r ../../../NtunlHost_linux_x64.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NtunlClient Release Asset (Windows x64)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NtunlClient_windows_x64.zip
          asset_name: NtunlClient_windows_x64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NtunlHost Release Asset (Windows x64)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NtunlHost_windows_x64.zip
          asset_name: NtunlHost_windows_x64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NtunlClient Release Asset (Linux x64)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NtunlClient_linux_x64.zip
          asset_name: NtunlClient_linux_x64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NtunlHost Release Asset (Linux x64)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NtunlHost_linux_x64.zip
          asset_name: NtunlHost_linux_x64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
